[package]
name = "playground-wasmtime-embed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
wasmtime = "19.0.0"
wasmtime-wasi = "19.0.0"
